name: Build STM32 firmware

on:
  push:
    tags:
      - 'v*'   # runs on tag push like v1.0.0

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install ARM toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi cmake ninja-build

      # ---------------------------------------------
      # Function to build a firmware variant
      # ---------------------------------------------
      - name: Build firmware variants
        run: |
          ./Tools/workflow_run.sh

      # ---------------------------------------------
      # Create GitHub Release
      # ---------------------------------------------
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
